### ISSUE TITLE
Questions regarding usage

### ISSUE THREAD

**Issue by absessive** [madebylotus/request_store-sidekiq#5]
I've tried using the gem, and just to verify in my worker I've got the following

    class SampleWorker < ActiveJob::Base
      before_enqueue do |job|
        puts "Tenant: #{RequestStore.store[:tenant_id]}"
      end
      before_perform do |job|
        puts "Tenant: #{RequestStore.store[:tenant_id]}"
      end
     
      def perform(user_id)
         # Worker code here
      end
    end

The `before_enqueue` works (as expected) and logs to the Rails log, while the `before_perform` logs to and returns nil for the `RequestStore.store` value. Why isn't the request store being reflected in the job?

**Comment by toxaq** [comment]
Looking at the code this is literally designed just to clear the RequestStore after each job. Before_enqueue will presumably be in your web process, so can access the RequestStore from there but before_process will be in your sidekiq job so won't have a preloaded RequestStore value.

The idea, I believe, is that if you set RequestStore in a worker, that value won't accidentally be left around for another worker to pick up, not that the request store will suddenly be available to any worker called from a different process.
